clear all 
close all
clc

% Gestione deelle differenti piattaforme da cui si chiama il codice

%base_directory = '/nfsd/biopetmri/BACKUP/Users/Marco/3T_Verona/SEL_candidates';
% ALTERNATIVA PC LOCALE 
base_directory = 'F:\Utente\TESI\';

data_path=fullfile(base_directory,'dati');
output_path=fullfile(base_directory,'output');

% elenco soggetti
list=dir(data_path);

jobdir=fullfile(base_directory,'code','Jobs');
if not(exist(jobdir,'dir'))
    mkdir(jobdir)
end
filename_qsub=fullfile(base_directory,'code','Jobs',['JacDet_sbatch_4_sienapd_slurm_' datestr(now,30) '.txt']);
ID_file_recap=fopen(filename_qsub,'w');

jobdir=fullfile(base_directory,'code','Jobs','Exex_slurm_sienapd');
if not(exist(jobdir,'dir'))
    mkdir(jobdir)
end
fprintf(ID_file_recap,['cd ' jobdir ' \n']);


for k=3:2:length(list)
    
    subjID = list(k).name;
    subj_path=fullfile(data_path, subjID);

    subj_data_list=dir(subj_path);
    
    % creo file job
                jobName=['JD_' num2str(subjID) '.job'];
                 
                ID_file=fopen(fullfile(jobdir, jobName),'wt');

                fprintf(ID_file,['#!/bin/bash\n'...
                    '#SBATCH --output ' jobName '.o%%j.txt\n'...
                    '#SBATCH --error ' jobName '.e%%j.txt\n'...
                    '#SBATCH --mail-user palombagia@dei.unipd.it\n'...
                    '#SBATCH --mail-type ALL\n'...
                    '#SBATCH --time 100:00:00\n'...
                    '#SBATCH --ntasks 1\n'...
                    '#SBATCH -c 4\n'...
                    '#SBATCH --exclude=gpu1,gpu2,runner-07,runner-08,runner-13,runner-14,runner-15,runner-16,runner-17,runner-18,runner-19\n'... 
                    '#SBATCH --partition allgroups\n'...
                    '#SBATCH --mem 16G\n'...
                    '\n'...
                    'export OMP_NUM_THREADS=4\n'...
                    'source /nfsd/opt/FSL/fsl603_env.sh\n'...
                    'export ANTSDIR=/nfsd/biopetmri/BACKUP/Users/Marco/3T_Verona/SEL_candidates/code/ANTs\n'...
                    'export PATH=$PATH:$ANTSDIR\n' ...
                    'export PATH=$PATH:/nfsd/biopetmri/BACKUP/Users/Marco/3T_Verona/SEL_candidates/code\n'...
                    'export PATH=$PATH:/nfsd/biopetmri/BACKUP/Users/Marco/3T_Verona/SEL_candidates/code/c3d\n'...
                    'export PATH=$PATH:/nfsd/biopetmri/BACKUP/Users/Marco/3T_Verona/SEL_candidates/Code/SEL/code_shell\n'...
                    'export PATH=$PATH:/nfsd/biopetmri/BACKUP/Users/Marco/3T_Verona/SEL_candidates/Code/SEL/code_shell/registration_sienapd\n'...
                    '\n'...
                    '\n'...
                    'T1_baseline=' fullfile(subj_path,baseline,'T1.nii.gz') '\n'...
                    'T1_follow=' fullfile(subj_path,followup,'T1.nii.gz') '\n'...
                    'T2_baseline=' fullfile(subj_path,baseline,'T2_to_T1.nii.gz') '\n'...
                    'T2_follow=' fullfile(subj_path,followup,'T2_to_T1.nii.gz') '\n'...
                    'T2_brain_baseline=' fullfile(subj_path,baseline,'T2_to_T1_brain.nii.gz') '\n'...
                    'T2_brain_follow=' fullfile(subj_path,followup,'T2_to_T1_brain.nii.gz') '\n'...                 
                    'FLAIR_brain_baseline=' fullfile(subj_path,baseline,'FLAIR_to_T1_brain.nii.gz') '\n'...
                    'FLAIR_brain_follow=' fullfile(subj_path,followup,'FLAIR_to_T1_brain.nii.gz') '\n'...
                    'mask_baseline=' fullfile(subj_path,baseline,'CT','BrainExtractionMask.nii.gz') '\n'...
                    'mask_follow=' fullfile(subj_path,followup,'CT','BrainExtractionMask.nii.gz') '\n'...
                    'output=' fullfile(output_path,subjID,[baseline '_' followup]) '\n'...
                    'registration_sienapd  $T1_baseline $T1_follow $FLAIR_brain_baseline $FLAIR_brain_follow $T2_baseline $T2_follow $T2_brain_baseline $T2_brain_follow $output -m1 $mask_baseline -m2 $mask_follow\n'...
                    '\n\n']);
                
               fclose(ID_file);
                
               fprintf(ID_file_recap,['sbatch ' fullfile(jobdir, jobName) '\n']);
    end
            
end

fclose(ID_file_recap);