#!/bin/bash

input1=$1
input2=$2
mask1=$3
mask2=$4
output=$5

/mnt/f/utente/tesi/software/code/sienapd $input1 $input2 -o $output -d -r1 $mask1 -r2 $mask2 -interp_flirt sinc

cd $output

######## ANTs Registration #########

fixed=A_halfwayto_B.nii.gz
moved=B_halfwayto_A.nii.gz

antsRegistration -d 3 --float 0 -o [matrice_T1,image_reg_T1.nii.gz] -n Linear -w [0.005,0.995] -u 0 -r [$fixed,$moved,1] -t Syn[0.1,3,0] -m CC[$fixed,$moved,1,4] -c [100x70x50x20,1e-6,20] -f 8x4x2x1 -s 3x2x1x0vox

#### Jacobian Determinant Image ####

CreateJacobianDeterminantImage 3 matrice_T11Warp.nii.gz image_detJ.nii.gz

mkdir registration_output

mv image_detJ.nii.gz $output/registration_output/

mv image_reg_T1.nii.gz $output/registration_output/


