clear all 
close all
clc

% Gestione deelle differenti piattaforme da cui si chiama il codice

%base_directory = '/nfsd/biopetmri/BACKUP/Users/Marco/3T_Verona/SEL_candidates';
% ALTERNATIVA PC LOCALE 
base_directory = 'F:\Utente\TESI\';

data_path=fullfile(base_directory,'data');
output_path=fullfile(base_directory,'output');

% elenco soggetti
list_output=dir(output_path);
list_data=dir(data_path);

jobdir=fullfile(base_directory,'code','Jobs');
if not(exist(jobdir,'dir'))
    mkdir(jobdir)
end
filename_qsub=fullfile(base_directory,'code','Jobs',['volume_sbatch_4_slurm_' datestr(now,30) '.txt']);
ID_file_recap=fopen(filename_qsub,'w');

jobdir=fullfile(base_directory,'code','Jobs','Exex_slurm_volume');
if not(exist(jobdir,'dir'))
    mkdir(jobdir)
end
fprintf(ID_file_recap,['cd ' strrep(jobdir,'\','/') ' \n']);


for t=3:1:length(list_output)
   
        subjID_output = list_output(3).name;
        subj_path_output=fullfile(output_path, subjID_output);
        subj_output_list=dir(subj_path_output);
        
   
                jobMatlabName=['M_SEL_JD_' num2str(str2double(subjID_output)) '.m'];
                 
                ID_file=fopen(fullfile(jobdir, jobMatlabName),'wt');
                
                
                fprintf(ID_file,['addpath(''/nfsd/biopetmri/BACKUP/Users/Marco/3T_Verona/SEL_candidates/code/NIFTI_toolbox/'')\n'...
                    'addpath(''/nfsd/biopetmri/BACKUP/Users/Marco/3T_Verona/SEL_candidates/SEL/code_matlab/volume'')\n'...
                    'SEL_1 = load_untouch_nii(''' strrep(fullfile(subj_path_output,subj_output_list(3).name,'volume','SEL_to_baseline_1.nii.gz'),'\','/') ''')' ';' '\n'...
                    'SEL_2 = load_untouch_nii(''' strrep(fullfile(subj_path_output,subj_output_list(3).name,'volume','SEL_to_baseline_2.nii.gz'),'\','/') ''')' ';' '\n'...
                    'SEL_3 = load_untouch_nii(''' strrep(fullfile(subj_path_output,subj_output_list(3).name,'volume','SEL_to_baseline_3.nii.gz'),'\','/') ''')' ';' '\n'...
                    'SEL_4 = load_untouch_nii(''' strrep(fullfile(subj_path_output,subj_output_list(3).name,'volume','SEL_to_baseline_4.nii.gz'),'\','/') ''')' ';' '\n'...
                    'lesions_prob_base = load_untouch_nii(''' strrep(fullfile(subj_path_output,subj_output_list(3).name,'volume','lesion_mask_baseline.nii.gz'),'\','/') ''')' ';' '\n'...
                    'lesions_prob_foll = load_untouch_nii(''' strrep(fullfile(subj_path_output,subj_output_list(3).name,'volume','lesion_mask_follow_reg.nii.gz'),'\','/') ''')' ';' '\n'...
                    'lesion_prob_base_img = lesion_prob_base.img > 0.5;' '\n'...                   
                    'lesion_prob_foll_img = lesion_prob_foll.img > 0.5;' '\n'...
                    'SEL_1 = SEL_1.img;' '\n'...
                    'SEL_2 = SEL_2.img;' '\n'...
                    'SEL_3 = SEL_3.img;' '\n'...
                    'SEL_4 = SEL_4.img;' '\n'...
                    '\n'...
                    '[volume_baseline,volume_follow] = volume_sel(lesion_prob_base_img,lesion_prob_foll_img,SEL_1,SEL_2,SEL_3,SEL_4);' '\n'...
                    'save(''' strrep(fullfile(subj_path_output,subj_output_list(3).name,'volume','volume_baseline'),'\','/') ''', ''volume_baseline'');' '\n' ...
                    'save(''' strrep(fullfile(subj_path_output,subj_output_list(3).name,'volume','volume_follow'),'\','/') ''', ''volume_follow'');' ]);

                    fclose(ID_file);
                
                jobName=['JD_' num2str(str2double(subjID_output)) '.job'];
                ID_file=fopen(fullfile(jobdir, jobName),'wt');
                
                fprintf(ID_file,['#!/bin/bash\n'...
                    '#SBATCH --output ' jobName '.o%%j.txt\n'...
                    '#SBATCH --error ' jobName '.e%%j.txt\n'...
                    '#SBATCH --mail-user palombagia@dei.unipd.it\n'...
                    '#SBATCH --mail-type ALL\n'...
                    '#SBATCH --ntasks 1\n'...
                    '#SBATCH -c 4\n'...
                    '#SBATCH --exclude=gpu1,gpu2,runner-07,runner-08,runner-13,runner-14,runner-15,runner-16,runner-17,runner-18,runner-19\n'... 
                    '#SBATCH --partition allgroups\n'...
                    '#SBATCH --mem 16G\n'...
                    '\n' ...
                    'pushd ' strrep(fullfile(jobdir),'\','/') '\n' ...
                    'matlab -nodisplay -nosplash -r "' strrep(jobMatlabName,'.m','')  ';exit" ']);
                
                fclose(ID_file);

                fprintf(ID_file_recap,['sbatch ' strrep(fullfile(jobdir,jobName),'\','/') '\n']);
                
       
end


  
  fclose(ID_file_recap)
        
