clear all 
close all
clc

% Gestione deelle differenti piattaforme da cui si chiama il codice

base_directory = '/nfsd/biopetmri/BACKUP/Users/Marco/3T_Verona/SEL_candidates/';
% ALTERNATIVA PC LOCALE 
%base_directory = 'F:\Utente\TESI\';

data_path=fullfile(base_directory,'data');
output_path=fullfile(base_directory,'output');

% elenco soggetti
list_data=dir(data_path);
list_output=dir(output_path);

jobdir=fullfile(base_directory,'code','Jobs');
if not(exist(jobdir,'dir'))
    mkdir(jobdir)
end
filename_qsub=fullfile(base_directory,'code','Jobs',['registration_volume_sbatch_4_slurm_' datestr(now,30) '.txt']);
ID_file_recap=fopen(filename_qsub,'w');

jobdir=fullfile(base_directory,'code','Jobs','Exex_slurm_registration_volume');
if not(exist(jobdir,'dir'))
    mkdir(jobdir)
end
fprintf(ID_file_recap,['cd ' strrep(jobdir,'\','/') ' \n']);

d = 2;
for k=3:2:length(list_data)
    d = d + 1;
    subjID_baseline = list_data(k).name;
    subjID_follow = list_data(k+1).name;
    subjID = list_output(d).name;    
    
    subj_path_baseline=fullfile(data_path, subjID_baseline);
    subj_path_follow=fullfile(data_path, subjID_follow);

    subj_data_list_baseline=dir(subj_path_baseline);
    subj_data_list_follow=dir(subj_path_follow);

    baseline = subj_data_list_baseline(3).name;
    followup = subj_data_list_follow(3).name;
   
        
        subjID_output = list_output(d).name;
        subj_path_output=fullfile(output_path, subjID_output);
        subj_output_list=dir(subj_path_output);
    
    % creo file job
                jobName=['JD_' num2str(str2num(subjID)) '.job'];
                 
                ID_file=fopen(fullfile(jobdir, jobName),'wt');
                
               
                fprintf(ID_file,['#!/bin/bash\n'...
                    '#SBATCH --output ' jobName '.o%%j.txt\n'...
                    '#SBATCH --error ' jobName '.e%%j.txt\n'...
                    '#SBATCH --mail-user palombagia@dei.unipd.it\n'...
                    '#SBATCH --mail-type ALL\n'...
                    '#SBATCH --ntasks 1\n'...
                    '#SBATCH -c 4\n'...
                    '#SBATCH --exclude=gpu1,gpu2,runner-07,runner-08,runner-13,runner-14,runner-15,runner-16,runner-17,runner-18,runner-19\n'... 
                    '#SBATCH --partition allgroups\n'...
                    '#SBATCH --mem 16G\n'...
                    '\n'...
                    'export OMP_NUM_THREADS=4\n'...
                    'source /nfsd/opt/FSL/fsl603_env.sh\n'...
                    'export ANTSDIR=/nfsd/biopetmri/BACKUP/DB_Neuro/Software/ANTs/bin_20160226\n' ...
                    'export PATH=$ANTSDIR:$PATH\n' ...
                    'export PATH=$PATH:/nfsd/biopetmri/BACKUP/Users/Marco/3T_Verona/SEL_candidates/code\n'...
                    'export PATH=$PATH:/nfsd/biopetmri/BACKUP/Users/Marco/3T_Verona/SEL_candidates/code/c3d\n'...
                    'export PATH=$PATH:/nfsd/biopetmri/BACKUP/Users/Marco/3T_Verona/SEL_candidates/SEL/code_shell\n'...
                    'export PATH=$PATH:/nfsd/biopetmri/BACKUP/Users/Marco/3T_Verona/SEL_candidates/SEL/code_shell/volume\n'...
                    '\n'...
                    '\n'...
                    'T1_baseline=' strrep(fullfile(subj_path_baseline,'T1.nii.gz'),'\','/') '\n'...
                    'T1_follow=' strrep(fullfile(subj_path_follow,'T1.nii.gz'),'\','/') '\n'...
                    'A_halfwayto_B_ANTs_SIENA=' strrep(fullfile(subj_path_output,subj_output_list(3).name,'registration_sienapd','FLAIR_T1','A_halfwayto_B_ANTs.mat'),'\','/') '\n'...
                    'A_halfwayto_B_ANTs_ROBUST=' strrep(fullfile(subj_path_output,subj_output_list(3).name,'registration_robust_template','FLAIR_T1','A_halfwayto_B_ANTs.mat'),'\','/') '\n'...
                    'SEL_1=' strrep(fullfile(subj_path_output,subj_output_list(3).name,'registration_sienapd','FLAIR_T1','Jacobian','SEL.nii.gz'),'\','/') '\n'...
                    'SEL_2=' strrep(fullfile(subj_path_output,subj_output_list(3).name,'registration_sienapd','T2_T1','Jacobian','SEL.nii.gz'),'\','/') '\n'...
                    'SEL_3=' strrep(fullfile(subj_path_output,subj_output_list(3).name,'registration_robust_template','FLAIR_T1','Jacobian','SEL.nii.gz'),'\','/') '\n'...
                    'SEL_4=' strrep(fullfile(subj_path_output,subj_output_list(3).name,'registration_robust_template','T2_T1','Jacobian','SEL.nii.gz'),'\','/') '\n'...
                    'lesion_mask_baseline=' strrep(fullfile(subj_path_baseline,'baseline_2ch','baseline_2ch_prob_1.nii.gz'),'\','/') '\n'...
                    'lesion_mask_follow=' strrep(fullfile(subj_path_follow,'baseline_2ch','baseline_2ch_prob_1.nii.gz'),'\','/') '\n'...
                    'output=' strrep(fullfile(output_path,subjID,[baseline '_' followup]),'\','/') '\n'...
                    'volume_sel $T1_baseline $T1_follow $lesion_mask_baseline $lesion_mask_follow $output $A_halfwayto_B_ANTs_SIENA $A_halfwayto_B_ANTs_ROBUST $SEL_1 $SEL_2 -sel_3 $SEL_3 -sel_4 $SEL_4 '\n']);
                    
                
               fclose(ID_file);
                
               fprintf(ID_file_recap,['sbatch ' strrep(fullfile(jobdir, jobName),'\','/') '\n']);
end
            
              

fclose(ID_file_recap);
